
import numpy as np
from viz.style import Style

class Model:
    def __init__(self, blend=1.0, cell_contraction=1.0, cell_coloring="default", hopf_L=None, hopf_R=None):
        self.vertices_4d = None
        self.edges = None
        self.colors = None
        self.style = Style()
        self.edge_colors = None
        self.edge_width_multipliers = None
        self.blend = blend
        self.cell_contraction = cell_contraction
        self.cell_coloring = cell_coloring
        self.hopf_L = hopf_L
        self.hopf_R = hopf_R
        self.cell_fibers = {}
        
        self.triangle_vertices_4d = None
        self.triangles = None
        self.triangle_normals_4d = None
        self.triangle_colors = None
        
        self.num_chains = 0
        self.triangles_by_chain = []
        
    def _generate_triangles(self):
        from scipy.spatial import ConvexHull
        
        vertices = self.vertices_4d
        if vertices is None or len(vertices) < 5:
            self.triangle_vertices_4d = np.array([], dtype=np.float32)
            self.triangles = []
            self.triangle_normals_4d = np.array([], dtype=np.float32)
            self.triangle_colors = np.array([], dtype=np.float32)
            return

        try:
            # In an N-dimensional space, scipy.spatial.ConvexHull mathematically computes the boundary 
            # of the convex polytope formed by the given vertices. The boundary of an N-dimensional 
            # convex hull is composed entirely of (N-1)-dimensional simplices. 
            # In our 4D space (N=4), an (N-1)-dimensional simplex is a 3-simplex, which is a tetrahedron.
            # This means ConvexHull will ALWAYS return a collection of tetrahedra, regardless of the 
            # true shapes of the 3D cells. For instance, the 120-cell's dodecahedral cells are artificially
            # decomposed (shattered) into arbitrary tetrahedra to satisfy this simplex requirement.
            hull = ConvexHull(vertices)
            equations = hull.equations
            simplices = hull.simplices
        except:
            self.triangle_vertices_4d = np.array([], dtype=np.float32)
            self.triangles = []
            self.triangle_normals_4d = np.array([], dtype=np.float32)
            self.triangle_colors = np.array([], dtype=np.float32)
            return

        # -------------------------------------------------------------------------
        # 1. Reconstruct True 3D Cells
        # -------------------------------------------------------------------------
        # To undo the artificial tetrahedral decomposition and recover the true 3D cells 
        # (like the dodecahedra of the 120-cell), we group the tetrahedra by the 4D hyperplane 
        # they lie on. If multiple tetrahedra share the exact same outward normal vector and 
        # offset (the hyperplane equation), they are coplanar in 4D space and therefore 
        # constitute parts of the exact same 3D cell.
        eqs_rounded = np.round(equations, 4)
        unique_eqs, inverse_indices = np.unique(eqs_rounded, axis=0, return_inverse=True)
        
        cells = []
        for i in range(len(unique_eqs)):
            simplex_indices = np.where(inverse_indices == i)[0]
            cell_verts = set()
            for idx in simplex_indices:
                cell_verts.update(simplices[idx])
            cells.append(list(cell_verts))

        t_verts = []
        t_tris = []
        t_norms = []
        t_colors = []
        
        # -------------------------------------------------------------------------
        # Dynamic Hopf Fibration Cell Clustering
        # -------------------------------------------------------------------------
        # We mathematically discover the chains of cells (fibers) by following 
        # the geometric orbit generated by c_next = L * c * R.
        cell_colors = []
        if self.cell_coloring == "hopf":
            from quaternion import q_mult, q_identity
            from .color_constants import COLOR_SEQUENCE, COLOR_VALUES
            
            L_quat = self.hopf_L if self.hopf_L is not None else q_identity
            R_quat = self.hopf_R if self.hopf_R is not None else q_identity
            
            centers = []
            for cell_v_indices in cells:
                c = np.mean(vertices[list(cell_v_indices)], axis=0)
                c_norm = np.linalg.norm(c)
                c = c / c_norm if c_norm > 1e-6 else np.array([1.0, 0.0, 0.0, 0.0])
                centers.append(c)
            centers = np.array(centers)
                
            chains = []
            
            if len(centers) == 600:
                # -------------------------------------------------------------------------
                # 600-Cell Symmetric Boerdijk-Coxeter Helix Generation
                # -------------------------------------------------------------------------
                # The 600-cell discrete Hopf fibration partitions the 600 tetrahedral cells 
                # into exactly 20 disjoint chains of 30 cells each. Each of these 30-cell 
                # chains physically forms a perfectly face-adjacent Boerdijk-Coxeter helix!
                # 
                # However, 4D screw motions (isometries of the form c -> L * c * R) have a 
                # subtle property: their translation distance varies depending on the invariant 
                # torus the points lie on. Because the 600 cells are scattered throughout the 
                # 3-sphere, a single global screw motion can only translate cells by exactly 
                # one face-adjacent step if those cells lie exactly on its perfect "equator". 
                # 
                # This mathematically proves why out of the 20 orbits generated by the screw 
                # motion, exactly 2 of them are "special" (they lie perfectly on the equators 
                # and step face-by-face), while the other 18 orbits "scatter" or skip faces 
                # because their translation displacement on off-equator tori does not match 
                # the physical face-to-face adjacency distance.
                # 
                # To construct all 20 mathematically perfect helices, we use the symmetry group:
                # 1. We use the screw motion to generate ONE perfect "equator" base helix.
                # 2. We use the rotational symmetry of the 600-cell (the 120 icosian vertices) 
                #    to iteratively rotate this perfect base helix into the 19 other disjoint 
                #    symmetric positions!
                
                from scipy.spatial import KDTree
                tree = KDTree(centers)
                
                # Step 1: Generate the perfect face-adjacent base helix (one of the 2 special equator helices)
                base_helix = []
                curr = centers[0]
                for _ in range(30):
                    _, idx = tree.query(curr)
                    base_helix.append(idx)
                    curr = q_mult(q_mult(L_quat, curr), R_quat)
                    
                # Step 2: Use symmetry group (the 600-cell vertices themselves) to rotate the base helix
                helices_set = set()
                group = vertices
                
                for qL in group:
                    if len(chains) == 20: break
                    for qR in group:
                        if len(chains) == 20: break
                        
                        # Rotate the perfect base helix into a new symmetry-invariant position
                        rotated_helix = []
                        for idx in base_helix:
                            mapped = q_mult(q_mult(qL, centers[idx]), qR)
                            _, m_idx = tree.query(mapped)
                            rotated_helix.append(m_idx)
                            
                        canonical = tuple(sorted(rotated_helix))
                        if canonical not in helices_set:
                            # Verify disjointness: the true 20 helices must perfectly partition the cells with zero overlap
                            overlap = False
                            for h in chains:
                                if len(set(h).intersection(set(rotated_helix))) > 0:
                                    overlap = True
                                    break
                            
                            if not overlap:
                                helices_set.add(canonical)
                                chains.append(rotated_helix)
            else:
                visited = set()
                for i in range(len(centers)):
                    if i in visited:
                        continue
                    
                    chain = []
                    curr = centers[i]
                    # Walk the orbit until it closes back on itself
                    for _ in range(len(centers) + 1):
                        distances = np.linalg.norm(centers - curr, axis=1)
                        idx = np.argmin(distances)
                        if idx in visited:
                            break
                        
                        chain.append(idx)
                        visited.add(idx)
                        curr = q_mult(q_mult(L_quat, curr), R_quat)
                    
                    chains.append(chain)
            
            self.num_chains = len(chains)
            self.cell_chains = []
            self.cells = cells
            
            # Pre-fill with white in case some cells are not visited (e.g. truncated models)
            default_color = [1.0, 1.0, 1.0, self.blend]
            cell_colors = [default_color] * len(cells)
            for fiber_id, chain in enumerate(chains):
                self.cell_chains.append(chain)
                color_name = COLOR_SEQUENCE[fiber_id % len(COLOR_SEQUENCE)]
                color_val = COLOR_VALUES[color_name] + [self.blend]
                
                for idx in chain:
                    sorted_tuple = tuple(sorted(list(cells[idx])))
                    self.cell_fibers[sorted_tuple] = fiber_id
                    cell_colors[idx] = color_val
        else:
            light_yellow = [1.0, 1.0, 0.5, self.blend]
            cell_colors = [light_yellow] * len(cells)

        chain_tris = {k: [] for k in range(self.num_chains)}
        chain_norms = {k: [] for k in range(self.num_chains)}
        chain_colors = {k: [] for k in range(self.num_chains)}

        for i, cell_v_indices in enumerate(cells):
            cell_v_indices = list(cell_v_indices)
            sorted_tuple = tuple(sorted(cell_v_indices))
            fiber_id = self.cell_fibers.get(sorted_tuple, 0)
            
            cell_verts_4d = vertices[cell_v_indices]
            cell_center = np.mean(cell_verts_4d, axis=0)
            
            # Apply cell contraction: Shrink the 3D cell towards its own center point
            # to visually separate adjacent 3D cells in the final 4D projection.
            contracted_verts = []
            for v in cell_verts_4d:
                contracted_verts.append(cell_center + (v - cell_center) * self.cell_contraction)
                
            # Map global vertex index to local contracted vertex index
            v_to_local = {global_idx: local_idx for local_idx, global_idx in enumerate(cell_v_indices)}
            
            # -------------------------------------------------------------------------
            # 2. Discover True 2D Faces (Ridges)
            # -------------------------------------------------------------------------
            # In a 4D strictly convex polytope, a 3D cell (facet) is bounded by 2D polygons (ridges).
            # By mathematical definition, a 2D ridge is the exact intersection of exactly two 
            # adjacent 3D cells.
            # 
            # Because we extracted the true 3D cells by grouping coplanar tetrahedra (in step 1),
            # any two cells that share 3 or more vertices are physically adjacent and share a 2D face!
            # (If they only shared 1 vertex, it would be a point intersection. If 2 vertices, an edge).
            # Therefore, the intersection of their vertex sets immediately yields the complete 
            # vertex set of their shared 2D polygonal face.
            faces = []
            for j, other_cell in enumerate(cells):
                if i == j:
                    continue
                common = set(cell_v_indices).intersection(set(other_cell))
                if len(common) >= 3:
                    faces.append(list(common))
                    
            cell_start_idx = len(t_verts)
            t_verts.extend(contracted_verts)
            
            # -------------------------------------------------------------------------
            # 3. Triangulate 2D Faces
            # -------------------------------------------------------------------------
            for face_v_indices in faces:
                # Get contracted coordinates for this face
                face_coords = [contracted_verts[v_to_local[v]] for v in face_v_indices]
                face_center = np.mean(face_coords, axis=0)
                
                face_center_idx = len(t_verts)
                t_verts.append(face_center)
                
                # To triangulate an arbitrary 3D/4D convex polygon (e.g., a pentagon), 
                # we must order its vertices angularly around its center. 
                # We perform SVD (Singular Value Decomposition) on the centered vertices. 
                # SVD identifies the principal components (directions of maximum variance).
                # Since the vertices are precisely coplanar, the first two principal components
                # (V[0] and V[1]) perfectly define the orthogonal 2D basis plane of the polygon.
                centered = np.array(face_coords) - face_center
                U, S, V = np.linalg.svd(centered, full_matrices=False)
                u_vec = V[0]
                v_vec = V[1]
                
                # Calculate the 2D angle of each vertex in this local coordinate system
                # and sort them to form a continuous loop around the polygon's perimeter.
                angles = np.arctan2(np.dot(centered, v_vec), np.dot(centered, u_vec))
                sort_order = np.argsort(angles)
                
                if len(sort_order) == 3:
                    # If the face is already a triangle (e.g., in the 600-cell or 24-cell),
                    # we do not need to subdivide it into 3 smaller triangles via the center.
                    v1_local_idx = v_to_local[face_v_indices[sort_order[0]]]
                    v2_local_idx = v_to_local[face_v_indices[sort_order[1]]]
                    v3_local_idx = v_to_local[face_v_indices[sort_order[2]]]
                    
                    tri = (cell_start_idx + v1_local_idx, cell_start_idx + v2_local_idx, cell_start_idx + v3_local_idx)
                    t_tris.append(tri)
                    if self.num_chains > 0: chain_tris[fiber_id].append(tri)
                    
                    normal = face_center - cell_center
                    norm_length = np.linalg.norm(normal)
                    if norm_length > 1e-6:
                        normal = normal / norm_length
                    else:
                        normal = np.array([0.0, 0.0, 0.0, 0.0])
                        
                    t_norms.append(normal)
                    t_colors.append(cell_colors[i])
                    if self.num_chains > 0:
                        chain_norms[fiber_id].append(normal)
                        chain_colors[fiber_id].append(cell_colors[i])
                else:
                    # For complex polygons (e.g., pentagons in the 120-cell),
                    # create triangles by connecting the face center to each sequential edge.
                    for k in range(len(sort_order)):
                        v1_local_idx = v_to_local[face_v_indices[sort_order[k]]]
                        v2_local_idx = v_to_local[face_v_indices[sort_order[(k+1)%len(sort_order)]]]
                        
                        tri = (face_center_idx, cell_start_idx + v1_local_idx, cell_start_idx + v2_local_idx)
                        t_tris.append(tri)
                        if self.num_chains > 0: chain_tris[fiber_id].append(tri)
                        
                        # The outward normal of the 2D face in the context of its 3D cell
                        # points from the 3D cell's center directly through the 2D face's center.
                        normal = face_center - cell_center
                        norm_length = np.linalg.norm(normal)
                        if norm_length > 1e-6:
                            normal = normal / norm_length
                        else:
                            normal = np.array([0.0, 0.0, 0.0, 0.0])
                            
                        t_norms.append(normal)
                        t_colors.append(cell_colors[i])
                        if self.num_chains > 0:
                            chain_norms[fiber_id].append(normal)
                            chain_colors[fiber_id].append(cell_colors[i])

        self.triangle_vertices_4d = np.array(t_verts, dtype=np.float32)
        self.triangles = t_tris
        self.triangle_normals_4d = np.array(t_norms, dtype=np.float32)
        self.triangle_colors = np.array(t_colors, dtype=np.float32)
        
        self.triangles_by_chain = []
        if self.num_chains > 0:
            for k in range(self.num_chains):
                self.triangles_by_chain.append((
                    chain_tris[k],
                    np.array(chain_norms[k], dtype=np.float32),
                    np.array(chain_colors[k], dtype=np.float32)
                ))
            
            self._compute_chain_groupings(centers, chains)
        else:
            self.chain_groupings = {"Single": []}
            self.chain_grouping_names = ["Single"]

    def _compute_chain_groupings(self, centers, chains):
        # -------------------------------------------------------------------------
        # Topological Fibration Grouping (SVD & Principal Angles)
        # -------------------------------------------------------------------------
        # The discrete fibers of the 24-cell, 120-cell, and 600-cell fibrations perfectly 
        # map onto the vertices of Platonic solids (Octahedron, Icosahedron, Dodecahedron) 
        # on the S^2 base space of the Hopf map.
        # 
        # We can computationally extract these structures by finding the exact 2D invariant 
        # plane of each fiber using Singular Value Decomposition (SVD):
        # https://en.wikipedia.org/wiki/Singular_value_decomposition
        # 
        # By calculating the principal angles between these 2D planes, we mathematically 
        # discover the concentric, interlocked "Clifford tori" (Toroidal Bundles) and 
        # orthogonal polar opposites (Antipodal Pairs).
        # https://en.wikipedia.org/wiki/Clifford_torus
        
        # 1. Compute the 2D plane spanning each chain using SVD
        chain_planes = []
        for chain in chains:
            pts = []
            for idx in chain:
                c = centers[idx]
                pts.append(c / np.linalg.norm(c))
            pts = np.array(pts)
            U, S, Vh = np.linalg.svd(pts)
            chain_planes.append(Vh[:2])

        # 2. Find Antipodal Pairs (planes that are perfectly orthogonal, 90 degrees)
        antipodal_pairs = []
        matched = set()
        for i in range(len(chains)):
            if i in matched: continue
            best_orthogonality = 1.0
            best_match = -1
            
            for j in range(len(chains)):
                if i == j: continue
                # Dot product matrix between basis vectors of the two planes
                dot_matrix = chain_planes[i] @ chain_planes[j].T
                orthogonality = np.linalg.norm(dot_matrix, ord=2)
                
                if orthogonality < best_orthogonality:
                    best_orthogonality = orthogonality
                    best_match = j
                    
            # A perfect orthogonal pair will have orthogonality < 1e-5
            if best_orthogonality < 1e-2:
                antipodal_pairs.append([i, best_match])
                matched.add(i)
                matched.add(best_match)
                
        # 3. Find Toroidal Bundles relative to Chain 0 (North Pole)
        pole_plane = chain_planes[0]
        distances = []
        for i in range(len(chain_planes)):
            dot_matrix = pole_plane @ chain_planes[i].T
            U, S, Vh = np.linalg.svd(dot_matrix)
            angle = np.arccos(np.clip(S[0], -1.0, 1.0)) * 180 / np.pi
            distances.append((i, angle))
            
        distances.sort(key=lambda x: x[1])
        
        current_angle = -1
        bundle = []
        bundles = []
        for i, angle in distances:
            if abs(angle - current_angle) > 1.0:
                if bundle:
                    bundles.append(bundle)
                bundle = []
                current_angle = angle
            bundle.append(i)
        if bundle:
            bundles.append(bundle)

        self.chain_groupings = {
            "Single": [[i] for i in range(len(chains))],
            "Antipodal Pairs": antipodal_pairs,
            "Toroidal Bundles": bundles
        }
        self.chain_grouping_names = ["Single", "Antipodal Pairs", "Toroidal Bundles"]
